# Generated by Django 3.2.16 on 2023-10-20 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_follow_user_following_unique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('id',)},
        ),
    ]
